// WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
console.log("Hello, CodeQL!");
console.log("I am here so that you don't fail in CI when there is no JavaScript or TypeScript code to analyze.");
