#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
import sys
from pathlib import Path

import skills_ref


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: ai-validate-skills.py <file1> [file2 ...]", file=sys.stderr)
        return 1

    all_errors = []

    for filepath_str in sys.argv[1:]:
        filepath = Path(filepath_str)

        skill_dir = filepath.parent
        skill_errors = skills_ref.validate(skill_dir)

        if skill_errors:
            bullet_list = "\n".join(f"  • {e}" for e in skill_errors)
            all_errors.append(f"✗ {filepath}: Validation errors in skill:\n{bullet_list}")
        else:
            print(f"✓ {filepath}: Skill is valid!")

    if all_errors:
        for error in all_errors:
            print(error, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
