#!/bin/bash
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
# Check Azure resource group costs using the Cost Management API
set -e

RED='\033[0;31m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

show_help() {
  cat << EOF
Usage: $0 --resource-group <rg> [OPTIONS]

Check Azure costs for a resource group using the Cost Management API.

Required:
  --resource-group <name>   Resource group name

Options:
  --subscription-id <id>    Subscription ID (uses current if not specified)
  --date-from <YYYY-MM-DD>  Start date (defaults to 364 days ago)
  --date-to <YYYY-MM-DD>    End date (defaults to today)
  --help                    Show this help

Examples:
  $0 --resource-group my-rg
  $0 --resource-group my-rg --date-from 2024-01-01 --date-to 2024-12-31
  $0 --resource-group my-rg --subscription-id <sub-id>
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --resource-group) RESOURCE_GROUP="$2"; shift 2 ;;
    --subscription-id) SUBSCRIPTION_ID="$2"; shift 2 ;;
    --date-from) DATE_FROM="$2"; shift 2 ;;
    --date-to) DATE_TO="$2"; shift 2 ;;
    --help) show_help ;;
    *) echo "Unknown option: $1. Run '$0 --help' for usage."; exit 1 ;;
  esac
done

[ -z "$RESOURCE_GROUP" ] && { echo -e "${RED}Error: --resource-group is required${NC}"; exit 1; }

SUBSCRIPTION_ID=${SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}
[ -n "$SUBSCRIPTION_ID" ] && az account set --subscription "$SUBSCRIPTION_ID" >/dev/null

# Verify the resource group exists
echo "Verifying resource group exists in Azure..."
if ! az group show --name "$RESOURCE_GROUP" --subscription "$SUBSCRIPTION_ID" &>/dev/null; then
  echo -e "${RED}Error: Resource group '$RESOURCE_GROUP' does not exist in subscription $SUBSCRIPTION_ID${NC}"
  exit 1
fi
echo -e "${BLUE}Resource group verified: $RESOURCE_GROUP${NC}"
echo ""

# Set date range
DATE_FROM=${DATE_FROM:-$(date -d "364 days ago" +%Y-%m-%d 2>/dev/null || date -v-364d +%Y-%m-%d)}
DATE_TO=${DATE_TO:-$(date +%Y-%m-%d)}

echo "=================================================="
echo "Azure Cost Analysis"
echo "=================================================="
echo "Subscription ID: $SUBSCRIPTION_ID"
echo "Resource Group:  $RESOURCE_GROUP"
echo "Time Period:     $DATE_FROM to $DATE_TO"
echo "=================================================="
echo ""

# Build the Resource Type query
QUERY_BODY=$(cat <<EOF
{
  "type": "ActualCost",
  "timeframe": "Custom",
  "timePeriod": {
    "from": "${DATE_FROM}T00:00:00Z",
    "to": "${DATE_TO}T23:59:59Z"
  },
  "dataset": {
    "granularity": "None",
    "aggregation": {
      "totalCost": {
        "name": "Cost",
        "function": "Sum"
      }
    },
    "grouping": [
      {
        "type": "Dimension",
        "name": "ResourceType"
      }
    ],
    "filter": {
      "dimensions": {
        "name": "ResourceGroup",
        "operator": "In",
        "values": ["$RESOURCE_GROUP"]
      }
    }
  }
}
EOF
)

echo "Cost Breakdown by Resource Type:"
echo "---------------------------------------------------"

az rest \
  --method POST \
  --url "https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/providers/Microsoft.CostManagement/query?api-version=2023-11-01" \
  --body "$QUERY_BODY" \
  --query "properties.{columns: columns, rows: rows}" \
  -o json > /tmp/cost_response_type.json

python3 << 'PYTHON_SCRIPT'
import json

with open('/tmp/cost_response_type.json', 'r') as f:
    data = json.load(f)

columns = data['columns']
rows = data['rows']

# Find column indices
col_names = [col['name'] for col in columns]
cost_idx = col_names.index('Cost')
resource_type_idx = col_names.index('ResourceType')
currency_idx = col_names.index('Currency')

# Print header
print(f"{'Resource Type':<50} {'Cost':>15} {'Currency':<10}")
print("-" * 80)

# Print rows and calculate total
total_cost = 0.0
currency_code = ""
has_currency = False

for row in rows:
    resource_type = row[resource_type_idx] if row[resource_type_idx] else "Unknown"
    cost = float(row[cost_idx])
    currency = row[currency_idx] if row[currency_idx] else ""

    print(f"{resource_type:<50} {cost:>15.2f} {currency:<10}")
    total_cost += cost
    if currency:
        currency_code = currency
        has_currency = True

print("-" * 80)
print(f"{'TOTAL':<50} {total_cost:>15.2f} {currency_code:<10}")

# Save currency info for later use
with open('/tmp/currency_info.txt', 'w') as f:
    f.write(f"{currency_code}\n{has_currency}")
PYTHON_SCRIPT

# Check if currency was available and show warning if not
if [ -f /tmp/currency_info.txt ]; then
    HAS_CURRENCY=$(tail -n 1 /tmp/currency_info.txt)

    if [ "$HAS_CURRENCY" = "False" ]; then
        echo ""
        echo "⚠️  WARNING: No currency information available in cost data"
        echo ""
    fi
fi

echo ""
echo ""

# Build the detailed query (by individual ResourceId)
DETAILED_QUERY_BODY=$(cat <<EOF
{
  "type": "ActualCost",
  "timeframe": "Custom",
  "timePeriod": {
    "from": "${DATE_FROM}T00:00:00Z",
    "to": "${DATE_TO}T23:59:59Z"
  },
  "dataset": {
    "granularity": "None",
    "aggregation": {
      "totalCost": {
        "name": "Cost",
        "function": "Sum"
      }
    },
    "grouping": [
      {
        "type": "Dimension",
        "name": "ResourceType"
      },
      {
        "type": "Dimension",
        "name": "ResourceId"
      }
    ],
    "filter": {
      "dimensions": {
        "name": "ResourceGroup",
        "operator": "In",
        "values": ["$RESOURCE_GROUP"]
      }
    }
  }
}
EOF
)

echo "Detailed Cost Breakdown by Resource:"
echo "---------------------------------------------------"

az rest \
  --method POST \
  --url "https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/providers/Microsoft.CostManagement/query?api-version=2023-11-01" \
  --body "$DETAILED_QUERY_BODY" \
  --query "properties.{columns: columns, rows: rows}" \
  -o json > /tmp/cost_response_detailed.json

python3 << 'PYTHON_SCRIPT'
import json
from collections import defaultdict

with open('/tmp/cost_response_detailed.json', 'r') as f:
    data = json.load(f)

columns = data['columns']
rows = data['rows']

# Find column indices
col_names = [col['name'] for col in columns]
cost_idx = col_names.index('Cost')
resource_type_idx = col_names.index('ResourceType')
resource_id_idx = col_names.index('ResourceId')
currency_idx = col_names.index('Currency')

# Group resources by type
resources_by_type = defaultdict(list)

# Read currency from first query
currency_code = ""
try:
    with open('/tmp/currency_info.txt', 'r') as f:
        currency_code = f.readline().strip()
except (FileNotFoundError, IOError):
    pass

for row in rows:
    resource_type = row[resource_type_idx] if row[resource_type_idx] else "Unknown"
    resource_id = row[resource_id_idx] if row[resource_id_idx] else "Unknown"
    resource_name = resource_id.split('/')[-1] if resource_id else "Unknown"
    cost = float(row[cost_idx])
    currency = row[currency_idx] if row[currency_idx] else ""

    resources_by_type[resource_type].append({
        'name': resource_name,
        'cost': cost,
        'currency': currency
    })

# Print grouped by resource type
for resource_type in sorted(resources_by_type.keys()):
    resources = resources_by_type[resource_type]
    type_total = sum(r['cost'] for r in resources)

    # Print resource type header with total
    print("")
    print("=" * 100)
    print(f"Resource Type: {resource_type}")
    print(f"Subtotal: {type_total:.2f} {currency_code}")
    print("=" * 100)
    print(f"{'Resource Name':<70} {'Cost':>15} {'Currency':<10}")
    print("-" * 100)

    # Print individual resources
    for resource in sorted(resources, key=lambda x: x['cost'], reverse=True):
        name_display = resource['name'][:68] + ".." if len(resource['name']) > 70 else resource['name']
        print(f"  {name_display:<68} {resource['cost']:>15.2f} {resource['currency']:<10}")

    print("-" * 100)

PYTHON_SCRIPT

echo ""
