#!/bin/bash
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
# Check Azure RBAC permissions for managed identities or app registrations
set -e

RED='\033[0;31m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

show_help() {
  cat << EOF
Usage: $0 --client-id <id> [OPTIONS]

Check Azure RBAC permissions for a managed identity or app registration.

Required:
  --client-id <id>          Client ID to check

Options:
  --subscription-id <id>    Subscription ID (uses current if not specified)
  --show-resources          List resources managed by this identity
  --help                    Show this help

Examples:
  $0 --client-id 12345678-1234-1234-1234-123456789abc
  $0 --client-id <id> --subscription-id <sub-id>
  $0 --client-id <id> --show-resources
EOF
  exit 0
}

SHOW_RESOURCES=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --client-id) CLIENT_ID="$2"; shift 2 ;;
    --subscription-id) SUBSCRIPTION_ID="$2"; shift 2 ;;
    --show-resources) SHOW_RESOURCES=true; shift ;;
    --help) show_help ;;
    *) echo "Unknown option: $1. Run '$0 --help' for usage."; exit 1 ;;
  esac
done

[ -z "$CLIENT_ID" ] && { echo -e "${RED}Error: --client-id is required${NC}"; exit 1; }

SUBSCRIPTION_ID=${SUBSCRIPTION_ID:-$(az account show --query id -o tsv | tr -d '\r')}
[ -n "$SUBSCRIPTION_ID" ] && az account set --subscription "$SUBSCRIPTION_ID" >/dev/null

echo -e "${BLUE}Checking permissions: ${CLIENT_ID}${NC}\n"
echo "============================================"
echo "Current Subscription"
echo "============================================"
az account show --query "{Name:name, SubscriptionId:id, TenantId:tenantId, State:state}" -o table
echo ""

# Check for group memberships (service principals only; MIs can't join groups)
# Fetched early so we can display a note to the user and use the IDs later to fetch group-based role assignments
GROUP_IDS=$(az rest --method GET --url "https://graph.microsoft.com/v1.0/servicePrincipals/${CLIENT_ID}/transitiveMemberOf/microsoft.graph.group" --query 'value[].id' -o tsv 2>/dev/null || true)
[ -n "$GROUP_IDS" ] && echo -e "${YELLOW}Note: Identity is member of $(echo "$GROUP_IDS" | grep -v '^$' | wc -l) group(s). Including group-based permissions...${NC}\n"

# Fetch all role assignments once (direct assignments)
TEMP_FILE=$(mktemp)
az role assignment list \
  --assignee "${CLIENT_ID}" \
  --all \
  --include-inherited \
  -o json > "$TEMP_FILE" 2>&1

# If there are group memberships, fetch those assignments too
if [ -n "$GROUP_IDS" ]; then
  # Fetch all group assignments in parallel using Python
  python3 - "$TEMP_FILE" "$CLIENT_ID" "$SUBSCRIPTION_ID" <<'PYGROUP'
import sys, json, subprocess

temp_file = sys.argv[1]
client_id = sys.argv[2]
subscription_id = sys.argv[3]

# Get group memberships (only works for service principals, not managed identities)
try:
    result = subprocess.run([
        'az', 'rest', '--method', 'GET',
        '--url', f'https://graph.microsoft.com/v1.0/servicePrincipals/{client_id}/transitiveMemberOf/microsoft.graph.group',
        '--query', 'value[].[id,displayName]', '-o', 'json'
    ], capture_output=True, text=True, timeout=10)

    if result.returncode != 0:
        sys.exit(0)  # Not a service principal or no groups

    groups = json.loads(result.stdout)
    group_map = {gid: gname for gid, gname in groups}

    # Load existing direct assignments
    with open(temp_file) as f:
        direct_assignments = json.load(f)

    # Fetch assignments for each group
    for group_id, group_name in groups:
        result = subprocess.run([
            'az', 'role', 'assignment', 'list',
            '--assignee', group_id,
            '--subscription', subscription_id,
            '--all',
            '-o', 'json'
        ], capture_output=True, text=True, timeout=10)

        if result.returncode == 0:
            group_assignments = json.loads(result.stdout)
            for assignment in group_assignments:
                assignment['_from_group'] = group_id
                assignment['_group_name'] = group_name
            direct_assignments.extend(group_assignments)

    # Save merged results
    with open(temp_file, 'w') as f:
        json.dump(direct_assignments, f)

except Exception as e:
    # Silently fail - just use direct assignments
    pass
PYGROUP
fi

# Check if the output is valid JSON
if ! python3 -c "import json; json.load(open('$TEMP_FILE'))" 2>/dev/null; then
  echo -e "${RED}Error querying role assignments:${NC}"
  cat "$TEMP_FILE" | head -5
  rm -f "$TEMP_FILE"
  exit 1
fi

# Process all assignments with a single Python script
python3 - "$TEMP_FILE" "$SUBSCRIPTION_ID" "$CLIENT_ID" <<'PYEOF'
import sys, json, re

with open(sys.argv[1]) as f:
    all_assignments = json.load(f)
subscription_id = sys.argv[2]
client_id = sys.argv[3]
current_sub_scope = f"/subscriptions/{subscription_id}"

# Get group names from assignments
group_names = {}
for a in all_assignments:
    if '_from_group' in a and a['_from_group'] not in group_names:
        group_names[a['_from_group']] = a.get('_group_name', a['_from_group'][:8])

# Build a map of roles at each scope for inheritance detection
roles_by_scope = {}
for assignment in all_assignments:
    scope = assignment['scope']
    role = assignment['roleDefinitionName']
    if scope not in roles_by_scope:
        roles_by_scope[scope] = set()
    roles_by_scope[scope].add(role)

def check_inheritance(role, current_scope, rg_name=None):
    """Check if a role is inherited from parent scopes"""
    inherited = []

    # Check resource group level (for resources only)
    if rg_name:
        rg_scope = f"{current_sub_scope}/resourceGroups/{rg_name}"
        if rg_scope in roles_by_scope and role in roles_by_scope[rg_scope]:
            inherited.append(f"resource group: {rg_name}")

    # Check subscription level
    if current_sub_scope in roles_by_scope and role in roles_by_scope[current_sub_scope] and current_scope != current_sub_scope:
        inherited.append("subscription")

    # Check management groups
    for scope in roles_by_scope:
        if '/managementGroups/' in scope and role in roles_by_scope[scope]:
            mg_match = re.search(r'/managementGroups/([^/]+)', scope)
            mg_name = mg_match.group(1) if mg_match else 'unknown'
            inherited.append(f"management group: {mg_name}")

    return inherited

# Subscription-Level Assignments
print("============================================")
print("Subscription-Level Role Assignments")
print("============================================")
print()

sub_assignments = [a for a in all_assignments if not '/resourceGroups/' in a['scope']]
if sub_assignments:
    for assignment in sub_assignments:
        role = assignment['roleDefinitionName']
        scope = assignment['scope']
        from_group = assignment.get('_from_group')
        group_suffix = f" [via group: {group_names.get(from_group, from_group[:8])}]" if from_group else ""

        if scope == current_sub_scope:
            print(f"  {role}{group_suffix}")
        else:
            mg_match = re.search(r'/managementGroups/([^/]+)', scope)
            if mg_match:
                print(f"  {role} (inherited from management group: {mg_match.group(1)}){group_suffix}")
            else:
                print(f"  {role} (inherited from: {scope}){group_suffix}")
else:
    print("  No subscription-level role assignments found.")
print()

# Resource Group-Level Assignments
print("============================================")
print("Resource Group-Level Role Assignments")
print("============================================")
print()

rg_assignments = []
for assignment in all_assignments:
    scope = assignment['scope']
    rg_match = re.match(r'/subscriptions/[^/]+/resourceGroups/([^/]+)$', scope)
    if rg_match:
        rg_name = rg_match.group(1)
        role = assignment['roleDefinitionName']
        inherited = check_inheritance(role, scope)
        from_group = assignment.get('_from_group')
        rg_assignments.append({'role': role, 'rg_name': rg_name, 'inherited': inherited, 'from_group': from_group})

if rg_assignments:
    for item in sorted(rg_assignments, key=lambda x: x['rg_name']):
        from_group = item.get('from_group')
        group_suffix = f" [via group: {group_names.get(from_group, from_group[:8])}]" if from_group else ""

        if item['inherited']:
            inh_str = " and ".join(item['inherited'])
            print(f"  {item['role']} (RG: {item['rg_name']}, inherited from {inh_str}, also directly assigned here){group_suffix}")
        else:
            print(f"  {item['role']} (RG: {item['rg_name']}){group_suffix}")
else:
    print("  No resource group-level role assignments found.")
print()

# Resource-Level Assignments
print("============================================")
print("Resource-Level Role Assignments")
print("============================================")
print()

resource_assignments = []
for assignment in all_assignments:
    scope = assignment['scope']
    role = assignment['roleDefinitionName']

    # Skip non-resource scopes
    if '/providers/' not in scope or '/providers/Microsoft.Authorization/roleAssignments' in scope:
        continue

    # Extract resource info
    clean_scope = re.sub(r'/providers/Microsoft\.Authorization/roleAssignments/[^/]+$', '', scope)
    resource_match = re.search(r'/providers/([^/]+)/([^/]+)/([^/]+)', clean_scope)
    if not resource_match:
        continue

    provider, resource_type, resource_name = resource_match.groups()
    full_type = f"{provider}/{resource_type}"

    # Check for sub-resources
    sub_resource_match = re.search(r'/providers/[^/]+/[^/]+/[^/]+/(.+)$', clean_scope)
    if sub_resource_match:
        resource_name = f"{resource_name}/{sub_resource_match.group(1)}"

    # Check inheritance
    rg_match = re.search(r'/resourceGroups/([^/]+)/', clean_scope)
    rg_name = rg_match.group(1) if rg_match else None
    inherited = check_inheritance(role, scope, rg_name)

    from_group = assignment.get('_from_group')
    resource_assignments.append({
        'role': role,
        'resource_type': full_type,
        'resource_name': resource_name,
        'inherited': inherited,
        'from_group': from_group
    })

if resource_assignments:
    for item in sorted(resource_assignments, key=lambda x: (x['resource_type'], x['resource_name'])):
        resource_display = f"{item['resource_type']}/{item['resource_name']}"
        from_group = item.get('from_group')
        group_suffix = f" [via group: {group_names.get(from_group, from_group[:8])}]" if from_group else ""

        if item['inherited']:
            inh_str = " and ".join(item['inherited'])
            print(f"  {item['role']} ({resource_display}, inherited from {inh_str}){group_suffix}")
        else:
            print(f"  {item['role']} ({resource_display}){group_suffix}")
else:
    print("  No resource-level role assignments found.")
print()
PYEOF

rm -f "$TEMP_FILE"

# Show managed resources if requested
if [ "$SHOW_RESOURCES" = true ]; then
  echo ""
  echo "============================================"
  echo "Managed Resources"
  echo "============================================"
  echo ""

  # Get resource groups where identity has Contributor/Owner/RBAC Admin
  RESOURCE_GROUPS=$(az role assignment list --assignee "$CLIENT_ID" --subscription "$SUBSCRIPTION_ID" --all -o json 2>/dev/null | python3 -c '
import sys, json
rgs = set()
for item in json.load(sys.stdin):
    scope, role = item.get("scope", ""), item.get("roleDefinitionName", "")
    if "/resourceGroups/" in scope and "/providers/" not in scope:
        if role in ["Contributor", "Owner", "Role Based Access Control Administrator"]:
            rgs.add(scope.split("/resourceGroups/")[1].split("/")[0])
print("\n".join(sorted(rgs)))
')

  if [ -z "$RESOURCE_GROUPS" ]; then
    echo "  No managed resource groups found (requires Contributor/Owner/RBAC Admin roles at RG level)"
    echo ""
  else
    echo "$RESOURCE_GROUPS" | while read -r RG_NAME; do
      echo "📦 Resource Group: $RG_NAME"
      echo ""

      az resource list --resource-group "$RG_NAME" -o json 2>/dev/null | python3 -c "
import sys, json
resources = json.load(sys.stdin)
if not resources:
    print('  No resources found')
    sys.exit(0)

print(f'  Total: {len(resources)} resources\n')
print('  {:<40} {:<45} {:<10} {:<20} {:<15} {:<12}'.format(
    'Name', 'Type', 'Location', 'Created', 'Changed', 'State'))
print('  ' + '-' * 142)

for r in resources:
    name = (r.get('name') or 'N/A')[:39]
    rtype = (r.get('type') or 'N/A')[:44]
    location = (r.get('location') or 'N/A')[:9]
    created = (r.get('createdTime') or 'N/A')[:19].replace('T', ' ').split('+')[0] if r.get('createdTime') else 'N/A'
    changed = (r.get('changedTime') or 'N/A')[:19].replace('T', ' ').split('+')[0] if r.get('changedTime') else 'N/A'
    state = (r.get('provisioningState') or 'N/A')[:11]

    print('  {:<40} {:<45} {:<10} {:<20} {:<15} {:<12}'.format(
        name, rtype, location, created, changed, state))
"
      echo ""
    done
  fi

  echo ""
  echo "============================================"
  echo "Visible Resource Groups"
  echo "============================================"
  echo ""

  # List all RGs that the identity can see (has any permission on)
  ALL_VISIBLE_RGS=$(az group list --subscription "$SUBSCRIPTION_ID" -o json 2>/dev/null | python3 -c '
import sys, json
rgs = [rg["name"] for rg in json.load(sys.stdin)]
print("\n".join(sorted(rgs)))
')

  if [ -z "$ALL_VISIBLE_RGS" ]; then
    echo "  No resource groups visible to this identity"
    echo ""
  else
    RG_COUNT=$(echo "$ALL_VISIBLE_RGS" | wc -l)
    echo "  Total: $RG_COUNT resource group(s)"
    echo ""
    echo "$ALL_VISIBLE_RGS" | while read -r RG_NAME; do
      echo "  • $RG_NAME"
    done
    echo ""
  fi
fi
