#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

# Validates that all workflows in .github/workflows have permissions defined for each job.
# This script also _disallows_ workflow-level permissions, which often become over-permissive
# when individual jobs need slightly different permissions. While it might be more repetitive
# to define permissions for each job, it is more secure and easier to audit.
import sys

import yaml

PERMISSIONS_KEY = "permissions"


def validate_workflow_permissions(workflow_path: str) -> bool:
    with open(workflow_path) as f:
        workflow = yaml.safe_load(f)

    if PERMISSIONS_KEY in workflow:
        print(f"✗ Workflow-level permissions found in {workflow_path}; define permissions per job instead.")
        return False

    all_jobs_valid = True
    for job_name, job in workflow["jobs"].items():
        if PERMISSIONS_KEY not in job:
            print(f"✗ Job '{job_name}' in {workflow_path} is missing permissions definition.")
            all_jobs_valid = False

    if all_jobs_valid:
        print(f"✓ All jobs in {workflow_path} have permissions defined.")

    return all_jobs_valid


# pre-commit passes in the affected filenames as arguments
workflow_files = sys.argv[1:]

has_violations = False
for workflow_file in workflow_files:
    if not validate_workflow_permissions(workflow_file):
        has_violations = True

if has_violations:
    sys.exit(1)
