#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

"""Convert a Markdown file to a well-formatted A3 landscape PDF.

This script reads a Markdown document (.md), converts it to HTML with
full support for tables, fenced code blocks, task-list checkboxes, and
a table of contents, then renders the HTML to a paginated PDF styled
for A3 landscape printing.

Usage::

    uv run tools/scripts/md_to_pdf.py <input.md> [output.pdf]

If *output.pdf* is omitted the PDF is written next to the input file
with the same stem (e.g. ``my-doc.md`` → ``my-doc.pdf``).

Dependencies are declared via inline PEP 723 script metadata, so
``uv run`` will automatically create an isolated environment with
everything needed — no manual install step required.

Examples::

    # Convert README.md to README.pdf in the same directory
    uv run tools/scripts/md_to_pdf.py README.md

    # Specify a custom output path
    uv run tools/scripts/md_to_pdf.py docs/design.md out/design.pdf
"""

# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "markdown>=3.5",
#   "weasyprint>=62.0",
# ]
# ///

import logging
import re
import sys
from pathlib import Path

import markdown
from weasyprint import HTML

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Stylesheet
#
# The CSS below targets WeasyPrint's rendering engine (which supports a
# useful subset of CSS Paged Media).  Key design decisions:
#
#   • A3 landscape gives enough horizontal room for wide tables and code.
#   • Headings use `page-break-after: avoid` so they aren't orphaned at
#     the bottom of a page.
#   • Code blocks preserve whitespace exactly (`white-space: pre`) so
#     ASCII diagrams render faithfully.
#   • Table rows alternate background colours for readability.
# ---------------------------------------------------------------------------
CSS = """
@page {
    size: A3 landscape;
    margin: 1.5cm;
}
body {
    font-family: "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #1a1a1a;
    max-width: 100%;
}
h1 { font-size: 20pt; border-bottom: 2px solid #0078d4; padding-bottom: 6px; margin-top: 24px; }
h2 { font-size: 16pt; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 20px; page-break-after: avoid; }
h3 { font-size: 13pt; margin-top: 16px; page-break-after: avoid; }

/* Code blocks - crucial for the ASCII diagram */
pre {
    background-color: #f6f8fa;
    border: 1px solid #d0d7de;
    border-radius: 6px;
    padding: 12px;
    overflow-x: visible;
    white-space: pre;
    word-wrap: normal;
    font-family: "Cascadia Code", "Fira Code", "Consolas", "Courier New", monospace;
    font-size: 9.5pt;
    line-height: 1.3;
}
code {
    font-family: "Cascadia Code", "Fira Code", "Consolas", "Courier New", monospace;
    font-size: 9pt;
    background-color: #f0f0f0;
    padding: 1px 4px;
    border-radius: 3px;
}
pre code {
    background: none;
    padding: 0;
    font-size: inherit;
}

/* Tables */
table {
    border-collapse: collapse;
    width: 100%;
    margin: 16px 0;
    font-size: 10pt;
    page-break-inside: avoid;
}
th {
    background-color: #0078d4;
    color: white;
    font-weight: 600;
    text-align: left;
    padding: 8px 12px;
    border: 1px solid #005a9e;
}
td {
    padding: 6px 12px;
    border: 1px solid #d0d7de;
    vertical-align: top;
}
tr:nth-child(even) {
    background-color: #f6f8fa;
}
tr:hover {
    background-color: #eef3f8;
}

/* Checkboxes */
ul { padding-left: 24px; }
li { margin-bottom: 4px; }

/* Horizontal rule */
hr { border: none; border-top: 1px solid #d0d7de; margin: 24px 0; }

/* Links */
a { color: #0078d4; text-decoration: none; }

/* Strong */
strong { color: #1a1a1a; }

/* Blockquote-style callouts */
blockquote {
    border-left: 4px solid #0078d4;
    margin: 16px 0;
    padding: 8px 16px;
    background-color: #f0f7ff;
}
"""

# -- Precompiled regex patterns ----------------------------------------------
_CHECKED_BOX = re.compile(r"^(\s*)- \[x\] ", flags=re.MULTILINE)
_UNCHECKED_BOX = re.compile(r"^(\s*)- \[ \] ", flags=re.MULTILINE)
_THREE_SPACE_INDENT = re.compile(r"^   (- |\* )", flags=re.MULTILINE)
_LIST_ITEM = re.compile(r"\s*(- |\* |\d+\. )")

_EMPTY_LIST_ITEM = re.compile(r"<li>\s*</li>")
_LIST_ITEM_WRAPPED_IN_PARAGRAPH = re.compile(r"<li>\s*<p>")
_PARAGRAPH_END_IN_LIST_ITEM = re.compile(r"</p>\s*</li>")
_PARAGRAPH_BOUNDARY = re.compile(r"</p>\s*<p>")

_MARKDOWN_EXTENSIONS = ("md", "markdown", "mdown", "mkd", "txt")


def preprocess_md(text: str) -> str:
    """Normalise Markdown quirks that trip up Python-Markdown.

    Python-Markdown (https://python-markdown.github.io/) is stricter than
    most editors and renderers (GitHub, Obsidian, …) about checkbox syntax,
    nested-list indentation, and blank-line placement.  This function
    patches the raw text so the parser produces correct HTML.
    """
    # -- 1. Checkboxes -------------------------------------------------------
    # Replace GFM-style task-list markers with Unicode equivalents.
    text = _CHECKED_BOX.sub(r"\1- ☑ ", text)
    text = _UNCHECKED_BOX.sub(r"\1- ☐ ", text)

    # -- 2. Sub-list indentation ---------------------------------------------
    # Convert 3-space indent (common under numbered parents like
    # "3. Item:\n   - sub") to the 4 spaces Python-Markdown expects.
    text = _THREE_SPACE_INDENT.sub(r"    \1", text)

    # -- 3. Blank line before list blocks ------------------------------------
    # Walk line-by-line and insert a blank line before the first list item
    # whenever the previous line is a regular paragraph (not a list item
    # and not already blank).
    lines = text.split("\n")
    result: list[str] = []
    for i, line in enumerate(lines):
        is_list_item = bool(_LIST_ITEM.match(line))
        if is_list_item and i > 0:
            prev = lines[i - 1]
            prev_is_list = bool(_LIST_ITEM.match(prev))
            prev_is_blank = prev.strip() == ""
            if not prev_is_list and not prev_is_blank:
                result.append("")  # insert blank line before list start
        result.append(line)

    return "\n".join(result)


def _postprocess_html(html: str) -> str:
    """Clean up HTML artefacts that cause WeasyPrint rendering issues.

    Python-Markdown produces valid but inconvenient HTML in a few cases
    that WeasyPrint renders poorly (e.g. bullets and text on separate
    lines).  This function patches those patterns.
    """
    # Remove empty <li> elements emitted from stray blank lines.
    html = _EMPTY_LIST_ITEM.sub("", html)

    # Unwrap <p> inside <li> — "loose lists" cause WeasyPrint to render
    # the bullet and its text on separate lines.
    html = _LIST_ITEM_WRAPPED_IN_PARAGRAPH.sub("<li>", html)
    html = _PARAGRAPH_END_IN_LIST_ITEM.sub("</li>", html)

    # Collapse remaining mid-item <p> boundaries into line breaks.
    html = _PARAGRAPH_BOUNDARY.sub("<br/>", html)

    return html


def convert(src: Path, out: Path) -> None:
    """Convert a Markdown file to a styled PDF.

    Reads *src*, preprocesses it for Python-Markdown compatibility,
    renders to HTML, post-processes away rendering artefacts, and
    writes a paginated PDF to *out* using WeasyPrint.

    Args:
        src: Path to the input Markdown file.
        out: Path where the output PDF will be written.
    """
    md_text = preprocess_md(src.read_text(encoding="utf-8"))

    # Markdown → HTML with extensions for tables, fenced code, TOC anchors,
    # and sane list-boundary handling.
    html_body = _postprocess_html(
        markdown.markdown(
            md_text,
            extensions=["tables", "fenced_code", "toc", "sane_lists"],
        )
    )

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>{CSS}</style>
</head>
<body>
{html_body}
</body>
</html>"""

    # Ensure the output directory exists (e.g. "out/report.pdf" when out/
    # hasn't been created yet).
    out.parent.mkdir(parents=True, exist_ok=True)

    HTML(string=full_html).write_pdf(str(out))
    logger.info("PDF written to %s  (%.0f KB)", out, out.stat().st_size / 1024)


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    src = Path(sys.argv[1]).resolve()
    if not src.exists():
        print(f"Error: {src} does not exist", file=sys.stderr)
        sys.exit(1)

    if src.suffix.lstrip(".").lower() not in _MARKDOWN_EXTENSIONS:
        logger.warning(
            "Input file %s does not look like Markdown (expected %s). Proceeding anyway.",
            src.name,
            ", ".join(f".{ext}" for ext in _MARKDOWN_EXTENSIONS),
        )

    # Default output path: same directory & stem as the input, with .pdf
    out = Path(sys.argv[2]).resolve() if len(sys.argv) >= 3 else src.with_suffix(".pdf")

    convert(src, out)
