#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
"""Pre-commit hook that autogenerates the list of Pulumi project options
in workflow_dispatch inputs for pulumi-deploy-production.yml and
pulumi-destroy-staging.yml.

Mono-project repos (infra/app): options = ["all"]
Multi-project repos (infra/projects/): options = ["all", "<name>", ...]
"""

import os
import sys
from pathlib import Path

REPO_ROOT = Path(os.getcwd())
THIS_FILE = Path(__file__).relative_to(REPO_ROOT)

MONO_PROJECT_DIR = Path("infra/app")
MULTI_PROJECT_ROOT = Path("infra/projects")

START_MARKER = "# PROJECT_OPTIONS_START"
END_MARKER = "# PROJECT_OPTIONS_END"

WORKFLOWS = [
    ".github/workflows/pulumi-deploy-production.yml",
    ".github/workflows/pulumi-destroy-staging.yml",
]


def discover_project_options() -> list[str]:
    if MULTI_PROJECT_ROOT.is_dir():
        projects = sorted(
            child.name for child in MULTI_PROJECT_ROOT.iterdir() if child.is_dir() and (child / "Pulumi.yml").exists()
        )
        return ["all", *projects]
    return ["all"]


def update_workflow(workflow_filepath: str, options: list[str]) -> None:
    with open(workflow_filepath) as f:
        contents = f.read()

    has_start = START_MARKER in contents
    has_end = END_MARKER in contents

    if has_start != has_end:
        print(
            f"Error: {workflow_filepath} has {START_MARKER if has_start else END_MARKER} "
            f"but is missing {END_MARKER if has_start else START_MARKER}",
            file=sys.stderr,
        )
        sys.exit(1)

    if not has_start:
        return

    start_index = contents.index(START_MARKER) + len(START_MARKER)
    end_index = contents.index(END_MARKER)

    new_contents = "\n".join(
        [
            contents[:start_index],
            f"# This list is autogenerated by {THIS_FILE} -- Do not edit directly",
            "        options:",
            *[f"          - {opt}" for opt in options],
            contents[end_index:],
        ]
    )

    with open(workflow_filepath, "w") as f:
        f.write(new_contents)


def main() -> None:
    options = discover_project_options()
    for workflow in WORKFLOWS:
        if Path(workflow).exists():
            update_workflow(workflow, options)


if __name__ == "__main__":
    main()
