#!/bin/bash
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

# Prevent the use of __all__ exports in Python files
if grep --quiet "__all__" "$1"; then
    echo "Error: Usage of __all__ export is not allowed in $1"
    exit 1
fi
exit 0
