#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

"""
Validate that certain noqa directives suppressing rule violations include a justification comment.

Initial motivation:
    Coding agents will occasionally introduce local imports
    inside functions rather than placing them at the top of the file. While local
    imports are valid in some cases (e.g., avoiding circular imports, deferring
    expensive module loads), they should be the exception rather than the rule.

    By requiring justification for suppressing PLC0415 (import-outside-top-level),
    we ensure that developers and agents think carefully about why a local import
    is necessary and document the reasoning for future maintainers.

How it works:
    This script checks Python files for noqa directives that suppress specific rules
    (configured in RULES_REQUIRING_JUSTIFICATION). To avoid false positives,
    the script verifies that Ruff would actually report the violation if the noqa
    comment were removed.

    Valid:   # noqa: PLC0415 # avoiding circular import with foo module
    Valid:   # noqa: PLC0415 # deferred import for performance
    Invalid: # noqa: PLC0415
    Invalid: # noqa: PLC0415 #

Usage:
    py-validate-noqa-justifications.py <file1> [file2 ...]

Exit codes:
    0: All noqa directives have required justifications
    1: One or more noqa directives are missing justifications
"""

import json
import re
import subprocess
import sys
from pathlib import Path

# Rules that require justification when suppressed
# Format: rule_code -> human-readable description
RULES_REQUIRING_JUSTIFICATION = {
    "PLC0415": "local import",
    "TID251": "banned API usage",
    "E402": "module level import not at top of file",
}

# Compiled regex patterns for performance
# Bare noqa: # noqa (suppresses all rules)
_BARE_NOQA_PATTERN = re.compile(r"#\s*noqa\s*($|#)", re.IGNORECASE)
# Justification comment after noqa directive
_JUSTIFICATION_PATTERN = re.compile(r"#\s*\S+")


def get_ruff_violations(filepath: Path, rule_codes: list[str]) -> dict[str, set[int]]:
    """Run Ruff on a file and return line numbers with violations for each rule.

    Uses --ignore-noqa to find all violations regardless of suppression comments.

    Args:
        filepath: The file to check
        rule_codes: List of rule codes to check for

    Returns:
        Dict mapping rule_code -> set of line numbers with violations
    """
    violations: dict[str, set[int]] = {code: set() for code in rule_codes}

    result = subprocess.run(
        [
            "uvx",
            "ruff",
            "check",
            "--select",
            ",".join(rule_codes),
            "--ignore-noqa",
            "--output-format",
            "json",
            str(filepath),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    if result.returncode == 0:
        # No violations
        return violations

    parsed = json.loads(result.stdout)
    for v in parsed:
        code = v.get("code")
        location = v.get("location", {})
        row = location.get("row")
        if code in violations and row is not None:
            violations[code].add(row)

    return violations


def check_file(filepath: Path) -> list[str]:
    """Check a file for noqa directives missing justifications.

    Returns a list of error messages.
    """
    errors = []

    try:
        content = filepath.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        return [f"{filepath}: Could not read file: {e}"]

    lines = content.splitlines()
    rule_codes = list(RULES_REQUIRING_JUSTIFICATION.keys())

    # Run Ruff with --ignore-noqa to find all violations regardless of suppression
    violations_by_rule = get_ruff_violations(filepath, rule_codes)

    for rule_code, description in RULES_REQUIRING_JUSTIFICATION.items():
        violation_lines = violations_by_rule.get(rule_code, set())
        if not violation_lines:
            continue

        # Compiled pattern to match noqa directive containing this specific rule
        # Matches: # noqa: PLC0415 or # noqa: F401, PLC0415, etc.
        specific_noqa_pattern = re.compile(rf"#\s*noqa:\s*[A-Z0-9,\s]*\b{rule_code}\b", re.IGNORECASE)

        for line_num in violation_lines:
            if line_num > len(lines):
                continue

            line = lines[line_num - 1]

            # Fast path: skip regex work if line doesn't contain 'noqa'
            if "noqa" not in line.lower():
                # Line has violation but no noqa - Ruff will catch this separately
                continue

            # Check for specific rule noqa or bare noqa
            specific_match = specific_noqa_pattern.search(line)
            bare_match = _BARE_NOQA_PATTERN.search(line)

            if not specific_match and not bare_match:
                # Line has violation but no noqa - Ruff will catch this separately
                continue

            # Determine which match to use for finding justification
            if specific_match:
                noqa_end = specific_match.end()
            elif bare_match:
                # Bare noqa - find where it ends
                noqa_end = bare_match.end() - len(bare_match.group(1))  # Exclude the captured ($|#)
            else:
                continue

            rest_of_line = line[noqa_end:].strip()

            # Check if there's a justification after the noqa directive
            # Valid: # noqa: PLC0415 # avoiding circular import
            # Valid: # noqa # avoiding circular import
            # Invalid: # noqa: PLC0415
            # Invalid: # noqa
            # Invalid: # noqa #
            # Fast path: no '#' means no justification comment
            has_justification = "#" in rest_of_line and _JUSTIFICATION_PATTERN.search(rest_of_line)

            if not has_justification:
                errors.append(
                    f"{filepath}:{line_num}: {rule_code} ({description}) suppression (`noqa`) without justification. "
                    f"Do not just add a justification to silence this — reconsider whether the "
                    f"suppression is needed at all. The default action should be to fix the "
                    f"violation (e.g., move an import to the top of the file, switch to an "
                    f"approved API), not to suppress it. Only add a `noqa` if the violation "
                    f"genuinely cannot or should not be avoided, and explain the specific reason why. "
                    f"Example: # noqa: {rule_code} # <why this specific violation cannot be fixed>"
                )

    return errors


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: py-validate-noqa-justifications.py <file1> [file2 ...]", file=sys.stderr)
        return 1

    all_errors = []

    for filepath_str in sys.argv[1:]:
        filepath = Path(filepath_str)
        if filepath.suffix == ".py" and filepath.exists():
            errors = check_file(filepath)
            all_errors.extend(errors)

    if all_errors:
        for error in all_errors:
            print(error, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
