#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

# Check that the given uv.lock file meets the minimum release age requirement.

# Note that the uv cli has a --exclude-newer option, but this doesn't
# support checking the minimum age of dependencies in an existing lock file;
# it only applies when syncing / adding new dependencies.

# Additionally, it ignores the lock file entirely and looks at pyproject.toml,
# which doesn't fulfill the requirement. A pyproject.toml file can specify a
# very old min version while the actual pinned version in the lockfile may be
# much newer.
import sys
from dataclasses import dataclass
from datetime import UTC
from datetime import datetime
from datetime import timedelta
from typing import Any

import requests
import tomllib
from packaging.version import Version

NOW = datetime.now(UTC)
MIN_RELEASE_DAYS = 5
MAX_RELEASE_TIME = NOW - timedelta(days=MIN_RELEASE_DAYS)

SKIP_PACKAGES_SOURCED_FROM = [
    "editable",
    "virtual",
    "directory",
    "git",
]


@dataclass
class PackageViolation:
    lockfile_path: str
    name: str
    version: str
    release_age_days: int


def get_lockfile_violations(lockfile_path: str) -> list[PackageViolation]:
    with open(lockfile_path) as f:
        uv_lock = tomllib.loads(f.read())

    violations: list[PackageViolation] = []

    for package in uv_lock["package"]:
        package_source = package["source"]
        if any(package_source.get(key) for key in SKIP_PACKAGES_SOURCED_FROM):
            continue

        package_name = package["name"]
        package_version = package["version"]
        upload_time_strings = []

        if sdist := package.get("sdist"):
            upload_time_strings.append(sdist["upload-time"])
        if wheels := package.get("wheels"):
            for wheel in wheels:
                upload_time_strings.append(wheel["upload-time"])

        if not upload_time_strings:
            raise ValueError(
                f"{package_name} in {lockfile_path} has no upload times; cannot validate minimum release age."
            )

        for upload_time_str in upload_time_strings:
            upload_time = datetime.fromisoformat(upload_time_str)
            if upload_time > MAX_RELEASE_TIME:
                release_age_days = (NOW - upload_time).days
                violations.append(
                    PackageViolation(
                        lockfile_path=lockfile_path,
                        name=package_name,
                        version=package_version,
                        release_age_days=release_age_days,
                    )
                )
                break  # No need to check other upload times for this package

    return violations


def get_latest_valid_release_version_for_package(name: str) -> str | None:
    """
    Use the PyPI JSON API to find the latest release version of a package
    that meets the minimum release age requirement.

    https://docs.pypi.org/api/json/
    """
    try:
        response = requests.get(
            f"https://pypi.org/pypi/{name}/json",
            timeout=5,
        )
        response.raise_for_status()
    except requests.RequestException as err:
        print(f"⚠️  Warning: Could not fetch release data for package {name}: {err}")
        return None

    # `releases` is a dict mapping version strings to lists of release files.
    releases: dict[str, list[dict[str, Any]]] = response.json()["releases"]

    versions = [Version(v) for v in releases]
    versions = [v for v in versions if not any([v.is_prerelease, v.is_devrelease, v.is_postrelease])]

    for version in sorted(versions, reverse=True):
        files = releases[str(version)]
        if not files:
            continue

        upload_times = [datetime.fromisoformat(f["upload_time_iso_8601"]) for f in files]
        if all(u < MAX_RELEASE_TIME for u in upload_times):
            return version

    return None


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: py-validate-min-release-age.py <file1> [file2 ...]", file=sys.stderr)
        return 1

    all_violations: list[PackageViolation] = []

    for lockfile_path in sys.argv[1:]:
        all_violations.extend(get_lockfile_violations(lockfile_path))

    if not all_violations:
        return 0

    package_to_latest_valid_release: dict[str, str | None] = {p.name: None for p in all_violations}
    for name in package_to_latest_valid_release:
        package_to_latest_valid_release[name] = get_latest_valid_release_version_for_package(
            name,
        )

    print(f"✗ Found {len(all_violations)} dependencies that are not at least {MIN_RELEASE_DAYS} days old:")
    print()

    for v in all_violations:
        latest_valid_release = package_to_latest_valid_release[v.name]

        print(f"    [{v.lockfile_path}] {v.name}@{v.version} is only {v.release_age_days} days old.")

        if latest_valid_release is None:
            print(f"    Could not find a valid release for {v.name}.")
            print()
            continue

        print(f"    Latest valid release is: {v.name}@{latest_valid_release}")
        print(f"    To fix, run: 'uv add {v.name}=={latest_valid_release}' in the project introducing the violation.")
        print(f"    If {v.name} is a dependency of a dependency (rather than a direct dependency), ")
        print(f"    you can remove after pinning via `uv remove {v.name}`.")
        print()

    return 1


if __name__ == "__main__":
    sys.exit(main())
