#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

import json
import os
from pathlib import Path

with open(".github/workspace-members.json") as f:
    members = json.load(f)

failed_package = False

for workspace_name, packages in members.items():
    if workspace_name not in ("py", "infra"):
        continue

    for package in packages:
        package_path = package["path"]

        # Ensure there is a .vscode directory
        os.makedirs(f"{package_path}/.vscode", exist_ok=True)

        # Ensure each Python project has a .vscode/settings.json file
        # that points to the appropriate virtualenv as the default
        # Python interpreter path.
        settings_path = f"{package_path}/.vscode/settings.json"
        settings_json: dict = {}

        if os.path.exists(settings_path):
            with open(settings_path, encoding="utf-8") as f:
                content = f.read().strip()

            try:
                settings_json = json.loads(content)
            except json.JSONDecodeError as e:
                print(f"❌ ERROR: Invalid JSON in project '{package_path}'")
                print(f"   File: {settings_path}")
                print(f"   JSON Error: {e}")
                print(f"   Content preview: {content[:100]}...")
                print("   Please fix the JSON syntax or delete the file")
                failed_package = True
                continue

        python_interpreter_path = None
        match workspace_name:
            case "py":
                # Python projects have a shared virtualenv at the workspace root.
                # The path we set here should point however many levels up py/ is from the package's path.
                # For example, if the package is at py/apps/my-app, the path should be ../../.venv/bin/python
                levels_up = len(Path(package_path).relative_to("py").parents)
                python_interpreter_path = "/".join([".."] * levels_up + [".venv", "bin", "python"])
            case "infra":
                # Infra projects are self-contained; they each have their own
                # virtualenv.
                python_interpreter_path = ".venv/bin/python"
            case _:
                # Should not reach here due to earlier continue
                raise ValueError(f"Unexpected workspace name: {workspace_name}")

        settings_json["python.defaultInterpreterPath"] = python_interpreter_path

        with open(settings_path, "w", encoding="utf-8") as f:
            json.dump(settings_json, f, indent=4)
            f.write("\n")

        print(f"✓ Validated project directory '{package_path}'")

if failed_package:
    exit(1)
