#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

# This script keeps .github/workspace-members.json up to date with
# the uv workspace members, the pnpm workspace members, and the infra projects.
# This json file is consumed by other tools and workflows that need to iterate
# through all workspace packages.
import json
from pathlib import Path

import tomllib

roots_to_patterns = {
    "py": [
        # Common Python libs & apps
        "*/libs/*",
        "*/apps/*",
        # This project's libs & apps
        "libs/*",
        "apps/*",
    ],
    "ts": [
        # Common TypeScript libs & apps
        "*/libs/*",
        "*/apps/*",
        # This project's libs & apps
        "libs/*",
        "apps/*",
    ],
    "infra": [
        # Common Pulumi libs
        "common/libs/*",
        # Main infra project is either at app/ (new) or <customer>/ (legacy)
        "*",
    ],
}

members_json_filepath = ".github/workspace-members.json"

all_members = {}

root_dir = Path()

for workspace_root, patterns in roots_to_patterns.items():
    workspace_members = []
    for pattern in patterns:
        for project_path in root_dir.glob(f"{workspace_root}/{pattern}"):
            if not project_path.is_dir():
                continue

            project_name = None
            if (project_path / "pyproject.toml").exists():
                with open(project_path / "pyproject.toml", "rb") as f:
                    config = tomllib.load(f)
                project_name = config["project"]["name"]
            elif (project_path / "package.json").exists():
                with open(project_path / "package.json") as f:
                    config = json.load(f)
                project_name = config["name"]

            if not project_name:
                print(f"Could not determine project name for '{project_path}'; skipping")
                continue

            workspace_members.append(
                {
                    "name": project_name,
                    "path": str(project_path.relative_to(root_dir)),
                }
            )

    workspace_members.sort(key=lambda x: x["path"])

    all_members[workspace_root] = workspace_members

with open(root_dir / members_json_filepath, "w") as f:
    json.dump(all_members, f, indent=4)
    f.write("\n")

print(f"✓ Synchronized {members_json_filepath}")
