#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

# Keeps the multi-root VSCode workspace file in sync with the
# current workspace members defined in .github/workspace-members.json.
# See https://code.visualstudio.com/docs/editing/workspaces/multi-root-workspaces
import json


def main() -> None:
    with open(".github/workspace-members.json") as f:
        workspace_members = json.load(f)

    folders = []
    for workspace_name, members in workspace_members.items():
        for member in members:
            folders.append(
                dict(
                    name=f"[{workspace_name}] {member['name']}",
                    path=member["path"],
                )
            )

    workspace = {
        "folders": sorted(folders, key=lambda x: x["name"]),
    }

    workspace_filepath = "fde.code-workspace"

    with open(workspace_filepath, "w") as f:
        json.dump(workspace, f, indent=4)
        f.write("\n")

    print(f"✓ Created VS Code workspace file at {workspace_filepath}")


if __name__ == "__main__":
    main()
