#!/bin/bash
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

if [[ -f "CLAUDE.md" ]]; then
    cp CLAUDE.md .github/copilot-instructions.md
fi

# Function to sync a README to an instructions file
sync_readme_to_instructions() {
    local source_path="$1"
    local instructions_name="$2"
    local apply_to="$3"

    mkdir -p ".github/instructions"

    target_path=".github/instructions/${instructions_name}"

    if [[ -f "$source_path" ]]; then
        if [[ ! -f "$target_path" ]]; then
            touch "$target_path"
        fi

        {
            echo "---"
            echo "applyTo: \"${apply_to}\""
            echo "---"
            echo "<!-- Instructions taken from ${source_path} - Do not edit directly -->"
            echo ""
            cat "$source_path"
        } > "$target_path"
    fi
}

# evals README
sync_readme_to_instructions "evals/README.md" "prompt_evals.instructions.md" "**/evals/**"

# Python common library READMEs (targeted at apps or libraries consuming the common libs)
for readme in py/common/libs/*/README.md; do
    if [[ -f "$readme" ]]; then
        libname=$(basename $(dirname "$readme"))
        sync_readme_to_instructions "$readme" "py_${libname}.instructions.md" "**/py/**"
    fi
done

# Subdirectory CLAUDE.md files → scoped .github/instructions/ files
# (Root CLAUDE.md is already handled above as copilot-instructions.md)
while IFS= read -r -d '' claude_file; do
    claude_file="${claude_file#./}"
    dir_path=$(dirname "$claude_file")
    instructions_name="claude_${dir_path//\//_}.instructions.md"
    apply_to="${dir_path}/**"
    sync_readme_to_instructions "$claude_file" "$instructions_name" "$apply_to"
done < <(find . -name "CLAUDE.md" \
    -not -path "./CLAUDE.md" \
    -not -path "./.git/*" \
    -not -path "*/node_modules/*" \
    -print0 | sort -z)

# Sync .claude/skills/ → .agents/skills/ (Claude Code is source of truth)
if [[ -d ".claude/skills" ]]; then
    mkdir -p .agents/skills
    rm -rf .agents/skills/*
    cp -R .claude/skills/. .agents/skills/
fi
