#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

import json

required_scripts = (
    "build",
    "test",
    "run-eslint",
    "fix-eslint",
)

required_engines = {
    "node": ">=22.0.0 <23.0.0",
    "npm": ">=10.0.0",
    "pnpm": ">=10.16.1",
}

with open(".github/workspace-members.json") as f:
    packages = json.load(f)["ts"]

all_errors = []

for package in packages:
    package_path = package["path"]

    if "/api-client-" in package_path:
        print(f"⊘ Skipping auto-generated package '{package_path}'")
        continue

    with open(f"{package_path}/package.json") as f:
        package_json = json.load(f)

    scripts = package_json.get("scripts", {})
    errors = []

    for required_script in required_scripts:
        if required_script not in scripts:
            errors.append(f"  ✗ Missing required script '{required_script}'")

    package_engines = package_json.get("engines", {})
    for required_engine_name, required_engine_version in required_engines.items():
        actual_engine_version = package_engines.get(required_engine_name)
        if actual_engine_version != required_engine_version:
            errors.append(
                f"  ✗ Engine '{required_engine_name}' should be "
                f"'{required_engine_version}' but found '{actual_engine_version}'"
            )

    if errors:
        print(f"✗ Validation failed for '{package_path}':")
        for error in errors:
            print(error)
        all_errors.append((package_path, errors))
    else:
        print(f"✓ Validated project directory '{package_path}'")

if all_errors:
    print(f"\n❌ Validation failed for {len(all_errors)} package(s)")
    exit(1)
