#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt

"""
Verify that relative links in markdown files point to existing files.

Checks all .md files for relative links and verifies the targets exist.

Exit codes:
  0 - All links valid
  1 - Broken links found
"""

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(os.getcwd())

# Pattern to match markdown links: [text](path) or [text](path "title")
# Excludes URLs (http://, https://, mailto:, #anchors)
LINK_PATTERN = re.compile(r"\[([^\]]*)\]\(([^)]+)\)", re.MULTILINE)

# Skip external URLs and anchors
SKIP_PREFIXES = {
    "http://",
    "https://",
    "mailto:",
    "#",
    "tel:",
}

# Exclude common non-doc directories
EXCLUDE_DIRS = {
    ".git",
    "node_modules",
    ".venv",
    "__pycache__",
    ".uv",
    ".entire",
}


def is_relative_link(href: str) -> bool:
    """Check if a link is a relative file path (not URL or anchor)."""
    href = href.split()[0].strip("\"'")  # Handle titles like (path "title")
    return not any(href.startswith(prefix) for prefix in SKIP_PREFIXES)


def extract_path(href: str) -> str:
    """Extract the file path from a link href, removing titles and anchors."""
    # Remove title if present: (path "title") -> path
    href = href.split()[0].strip("\"'")
    # Remove anchor if present: path#anchor -> path
    href = href.split("#")[0]
    return href


def remove_code_blocks(content: str) -> str:
    """Remove fenced code blocks from content to avoid false positives."""
    # Remove fenced code blocks (``` ... ```)
    content = re.sub(r"```[\s\S]*?```", "", content)
    # Remove inline code (`...`)
    content = re.sub(r"`[^`]+`", "", content)
    return content


def verify_links(md_file: Path) -> list[tuple[int, str, str]]:
    """
    Verify all relative links in a markdown file.

    Returns list of (line_number, link_text, broken_path) for broken links.
    """
    content = md_file.read_text()

    # Remove code blocks to avoid false positives on type annotations
    content_no_code = remove_code_blocks(content)

    broken = []
    lines = content.split("\n")
    lines_no_code = content_no_code.split("\n")

    for line_num, (_line, line_no_code) in enumerate(zip(lines, lines_no_code, strict=False), 1):
        # Only check links that appear outside code blocks
        for match in LINK_PATTERN.finditer(line_no_code):
            link_text = match.group(1)
            href = match.group(2)

            if not is_relative_link(href):
                continue

            path = extract_path(href)
            if not path:  # Empty path after stripping anchor
                continue

            # If the path starts with a leading slash, it is relative to the repo root
            if path.startswith("/"):
                target = (REPO_ROOT / path.lstrip("/")).resolve()
            else:
                # Resolve relative to the markdown file's directory
                target = (md_file.parent / path).resolve()

            # Check if target exists
            if not target.exists():
                broken.append((line_num, link_text, path))

    return broken


def main() -> int:
    """Main entry point."""
    md_files = list(REPO_ROOT.glob("**/*.md"))

    md_files = [f for f in md_files if not any(excluded in f.parts for excluded in EXCLUDE_DIRS)]

    all_broken: list[tuple[Path, int, str, str]] = []

    for md_file in md_files:
        relative_path = md_file.relative_to(REPO_ROOT)
        broken = verify_links(md_file)

        for line_num, link_text, path in broken:
            all_broken.append((relative_path, line_num, link_text, path))

    if all_broken:
        print("Broken links found:\n")
        for file_path, line_num, link_text, path in all_broken:
            print(f"  {file_path}:{line_num}")
            print(f"    [{link_text}]({path})")
            print()
        print(f"Total: {len(all_broken)} broken link(s)")
        return 1

    print(f"Checked {len(md_files)} markdown files - all links valid")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Verify markdown links.")
    parser.add_argument(
        "--exclude-dirs",
        nargs="+",
        type=str,
        help="List of directories to exclude",
    )
    args = parser.parse_args()

    if args.exclude_dirs:
        EXCLUDE_DIRS.update(d.strip() for d in args.exclude_dirs)

    sys.exit(main())
