# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
"""Discover Pulumi projects using convention-based directory layout.

Mono-project repos: single project at infra/app
Multi-project repos: projects under infra/projects/<name>/

When project is "all":
  - If infra/projects/ exists, discovers all projects under it
  - Otherwise, falls back to infra/app (mono-project)
When a specific project name is provided:
  - Multi-project: resolves to infra/projects/<name>
  - Mono-project: rejects with an error (only "all" is valid)

Outputs relative paths from the repo root (e.g. "infra/app", "infra/projects/platform")
so they can be used directly as working-directory in workflow steps.

Usage:
    python run.py <project>

    project:  "all" to discover all projects, or a project name (e.g. "platform")

Writes outputs to the file specified by the $GITHUB_OUTPUT environment variable.
"""

import json
import os
import re
import sys
from pathlib import Path

MONO_PROJECT_DIR = Path("infra/app")
MULTI_PROJECT_ROOT = Path("infra/projects")
GITHUB_OUTPUT_FILE = os.environ["GITHUB_OUTPUT"]

# Project names must be simple directory names (alphanumeric, hyphens, underscores).
PROJECT_NAME_PATTERN = re.compile(r"^[A-Za-z0-9_-]+$")


def set_output(name: str, value: str) -> None:
    with open(GITHUB_OUTPUT_FILE, "a") as f:
        f.write(f"{name}={value}\n")


def is_pulumi_project(path: Path) -> bool:
    return (path / "Pulumi.yml").exists()


def is_multi_project_repo() -> bool:
    return MULTI_PROJECT_ROOT.is_dir()


def discover_projects() -> list[str]:
    """Find all immediate subdirectories of infra/projects/ that contain a Pulumi.yml."""
    projects: list[str] = []
    for child in sorted(MULTI_PROJECT_ROOT.iterdir()):
        if child.is_dir() and is_pulumi_project(child):
            projects.append(str(child))
    return projects


def main(project_input: str) -> None:
    is_multi_project = is_multi_project_repo()

    if project_input == "all":
        if is_multi_project:
            result = discover_projects()
            if not result:
                print(f"::error::No Pulumi projects found under '{MULTI_PROJECT_ROOT}'")
                sys.exit(1)
        else:
            if not is_pulumi_project(MONO_PROJECT_DIR):
                print(f"::error::No Pulumi project found at '{MONO_PROJECT_DIR}'")
                sys.exit(1)
            result = [str(MONO_PROJECT_DIR)]
    else:
        if not PROJECT_NAME_PATTERN.match(project_input):
            print(f"::error::Invalid project name '{project_input}'. Must match [A-Za-z0-9_-]+.")
            sys.exit(1)

        if not is_multi_project:
            if project_input == "app":
                # "app" is the conventional mono-project name — treat it as "all"
                result = [str(MONO_PROJECT_DIR)]
                set_output("projects", json.dumps(result))
                set_output("is-multi-project", "false")
                print(f"Resolved {len(result)} project(s): {result}")
                return
            print(
                f"::error::This is a mono-project repo (no '{MULTI_PROJECT_ROOT}' directory). "
                f"Only 'all' or 'app' are supported as input."
            )
            sys.exit(1)

        project_path = MULTI_PROJECT_ROOT / project_input
        if not is_pulumi_project(project_path):
            print(f"::error::'{project_input}' is not a valid Pulumi project (no Pulumi.yml in '{project_path}')")
            sys.exit(1)
        result = [str(project_path)]

    set_output("projects", json.dumps(result))
    set_output("is-multi-project", str(is_multi_project).lower())
    print(f"Resolved {len(result)} project(s): {result}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <project>", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
