# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
"""
Generates a user-delegation SAS token through Azure Front Door.

The SAS token is printed to stdout for capture by the calling shell script.
All configuration is read from environment variables.
"""
# /// script
# dependencies = [
#   "azure-identity==1.25.3",
#   "azure-storage-blob==12.28.0",
# ]
# ///

import os
from datetime import datetime
from datetime import timedelta
from datetime import timezone

from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient
from azure.storage.blob import generate_container_sas

afd_hostname = os.environ["AFD_HOSTNAME"]
account_name = os.environ["STORAGE_ACCOUNT"]
container_name = os.environ["CONTAINER_NAME"]
expiry_hours = int(os.environ["EXPIRY_HOURS"])

credential = DefaultAzureCredential()
blob_service = BlobServiceClient(
    account_url=f"https://{afd_hostname}",
    credential=credential,
)

start = datetime.now(timezone.utc)
expiry = start + timedelta(hours=expiry_hours)
udk = blob_service.get_user_delegation_key(start, expiry)

sas = generate_container_sas(
    account_name=account_name,
    container_name=container_name,
    user_delegation_key=udk,
    permission="racwdl",
    expiry=expiry,
    start=start,
)

print(sas)
