#!/usr/bin/env python3
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
"""Trigger the pulumi-set-secret GitHub Actions workflow to set a Pulumi encrypted secret.

Uploads the secret value as a temporary GitHub secret, then dispatches the workflow
which sets the secret in the Pulumi stack config and opens a PR with the changes.

Usage:
    ./run.py --stack <staging|production> --secret-name <name> [--project <name>] [--secret-value <value>]
"""

import argparse
import getpass
import json
import subprocess
import sys
import uuid


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, **kwargs)


def main() -> None:
    parser = argparse.ArgumentParser(description="Set a Pulumi encrypted secret via GitHub Actions.")
    parser.add_argument(
        "--stack", required=True, choices=["staging", "production"], help="Pulumi stack to set the secret in"
    )
    parser.add_argument("--secret-name", required=True, help="Name of the Pulumi secret to set")
    parser.add_argument("--project", default="app", help="Name of the Pulumi project under infra/ (default: 'app')")
    parser.add_argument("--secret-value", help="Value of the secret (will prompt interactively if not provided)")
    args = parser.parse_args()

    secret_value = args.secret_value
    if not secret_value:
        secret_value = getpass.getpass(f"? Paste the value of {args.secret_name} for {args.stack}: ")
    if not secret_value:
        print("Error: Secret value cannot be empty.", file=sys.stderr)
        sys.exit(1)

    gh_secret_name = "PULUMI_TEMP_SECRET_OBJECT"
    unique_id = str(uuid.uuid4())
    secret_object = json.dumps({"unique_id": unique_id, "secret_value": secret_value})

    print()
    run(["gh", "secret", "set", gh_secret_name, "--body", secret_object])

    workflow_args = [
        "-f",
        f"pulumi-stack-name={args.stack}",
        "-f",
        f"pulumi-secret-name={args.secret_name}",
        "-f",
        f"gh-secret-unique-id={unique_id}",
        "-f",
        f"project={args.project}",
    ]
    run(["gh", "workflow", "run", "pulumi-set-secret.yml", *workflow_args])

    print()
    print("A pull request will be created automatically. Check the workflow logs.")
    print()


if __name__ == "__main__":
    main()
