# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
#!/bin/bash
set -e

pulumi_stack_name=$1
pulumi_secret_name=$2
pulumi_secret_value=$3
gh_secret_name="PULUMI_TEMP_SECRET_OBJECT"

if [[ -z "$pulumi_stack_name" ||
      -z "$pulumi_secret_name" ||
      "$pulumi_stack_name" != "staging" && "$pulumi_stack_name" != "production"
]]; then
  echo "Usage: $0 <pulumi_stack_name> <pulumi_secret_name>"
  echo "  <pulumi_stack_name> must be 'staging' or 'production'"
  exit 1
fi

if [[ -z "$pulumi_secret_value" ]]; then
  read -s -p "? Paste the value of $pulumi_secret_name for $pulumi_stack_name: " pulumi_secret_value
fi

if [[ -z "$pulumi_secret_value" ]]; then
  echo "Error: Secret value cannot be empty."
  exit 1
fi

gh_secret_unique_id=$(uuidgen)

echo
echo

gh secret set \
  $gh_secret_name \
  --body "{\"unique_id\":\"$gh_secret_unique_id\",\"secret_value\":\"$pulumi_secret_value\"}"

gh workflow run \
  pulumi-set-secret.yml \
  -f pulumi-stack-name=$pulumi_stack_name \
  -f pulumi-secret-name=$pulumi_secret_name \
  -f gh-secret-unique-id=$gh_secret_unique_id \

echo
echo "A pull request will be created automatically. Check the workflow logs."
echo
