# ruff: noqa: E501
# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/microsoft/fde-mgmt
# Generates a Markdown table with a summary of a Pulumi preview located at PREVIEW_JSON_FILEPATH.

import json
import os
import subprocess
import tempfile

# Pulumi uses this value as a placeholder for "not yet known" during previews,
# leading to confusing diffs that suggest a dependency's ID has changed when
# in reality the dependency is being replaced and its ID is not yet known.
# https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/variables/runtime.unknownValue.html
PULUMI_UNKNOWN_PLACEHOLDER = "04da6b54-80e4-46f7-96ec-b56ff0331ba9"

pulumi_project_name = os.environ["PULUMI_PROJECT_NAME"]
pulumi_stack_name = os.environ["PULUMI_STACK_NAME"]
preview_artifact_url = os.environ["PREVIEW_ARTIFACT_URL"]
preview_json_filepath = os.environ["PREVIEW_JSON_FILEPATH"]
preview_markdown_filepath = os.environ["PREVIEW_MARKDOWN_FILEPATH"]
github_commit_sha = os.environ["GITHUB_HEAD_REF_SHA"]
github_workflow_name = os.environ["GITHUB_WORKFLOW"]
github_job_name = os.environ["GITHUB_JOB"]
github_workflow_run_url = "/".join(
    [
        os.environ["GITHUB_SERVER_URL"],
        os.environ["GITHUB_REPOSITORY"],
        "actions",
        "runs",
        os.environ["GITHUB_RUN_ID"],
    ]
)


def exec_cmd(cmd: list[str]) -> str:
    """Executes a command and returns the output as a string."""
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


with open(preview_json_filepath) as f:
    preview = json.load(f)

body = '<p align="center">'
body += '<img src="https://www.pulumi.com/images/logo/logo-on-white-box.svg?" width="150">'
body += "</p>"
body += f"\n\n# `{pulumi_project_name}-{pulumi_stack_name}` @ {github_commit_sha}"
body += "\n\n## Preview"

emoji_map = {
    "same": "⚪",
    "create": "🟢",
    "update": "🟡",
    "delete": "🔴",
    "replace": "🔄",
    "import": "📥",
    "read": "👁️",
}

for step in preview["steps"]:
    urn = step["urn"]
    op = step["op"]

    parts = urn.split("::")
    resource_name = parts[-1]
    resource_type = parts[-2]

    if resource_type == "pulumi:pulumi:Stack":
        continue

    emoji = emoji_map.get(op, "")

    old_state = step.get("oldState") or {}
    new_state = step.get("newState") or {}
    old_inputs = old_state.get("inputs") or {}
    new_inputs = new_state.get("inputs") or {}

    resource_id = new_state.get("id") or old_state.get("id") or "-"

    body += f"\n\n### {emoji} `{resource_type}: {resource_name}`"
    body += f"\n- Operation: **`{op}`**"
    body += f"\n- URN: `{urn}`"
    body += f"\n- ID: `{resource_id}`"

    # If the op is "replace", show the reasons for replacement.
    if op == "replace":
        replace_reasons = step.get("replaceReasons")
        if replace_reasons:
            body += "\n\n"
            body += "> [!CAUTION]\n"
            body += "> This resource is being **replaced** because the following properties were modified:"

            for reason in replace_reasons:
                body += f"\n> - `{reason}`"

    # Show diff between new and old inputs.
    if new_inputs != old_inputs:
        with tempfile.TemporaryDirectory() as tmpdir:
            old_filepath = os.path.join(tmpdir, "old.json")
            new_filepath = os.path.join(tmpdir, "new.json")
            with open(old_filepath, "w") as f:
                f.write(json.dumps(old_inputs, indent=2) + "\n")
            with open(new_filepath, "w") as f:
                f.write(json.dumps(new_inputs, indent=2) + "\n")

            diff_output = exec_cmd(
                [
                    "diff",
                    # Show 3 lines of context.
                    "--unified=3",
                    old_filepath,
                    new_filepath,
                ]
            )

        # Remove first two lines of diff (the temp filenames).
        diff_output = "\n".join(diff_output.splitlines()[2:])

        body += "\n\n```diff"
        body += f"\n{diff_output}"
        body += "\n```"

body += f"\n\n[Download full preview →]({preview_artifact_url})"

diagnostics = preview.get("diagnostics")
if diagnostics:
    body += "\n\n## Diagnostics"
    for diag in diagnostics:
        message = diag["message"]
        severity = diag["severity"]
        body += f"\n- `[{severity}]`: {message.strip()}"

summary = preview.get("changeSummary")
if summary:
    body += "\n\n## Summary"

    total_changes = 0
    for op, count in summary.items():
        if op != "same":
            total_changes += count
            emoji = emoji_map.get(op, "")
            body += f"\n- {emoji} {count} to {op}"

    same_changes = summary.get("same", 0)
    body += f"\n\n**{total_changes}** changes. {same_changes} unchanged."

body += '\n\n<p align="right">'
body += f'Generated by <a href="{github_workflow_run_url}">{github_workflow_name} / {github_job_name}</a> against {github_commit_sha}.'
body += "</p>"

body = body.replace(PULUMI_UNKNOWN_PLACEHOLDER, "<NOT_YET_KNOWN>")

with open(preview_markdown_filepath, "w") as f:
    f.write(body + "\n")
